export const SET_LANGUAGE = "SET_LANGUAGE";
export const GET_PAGE_PENDING = "GET_PAGE_PENDING";
export const GET_PAGE_SUCCESS = "GET_PAGE_SUCCESS";
export const GET_PAGE_FAILURE = "GET_PAGE_FAILURE";
export const SAVE_PAGE_PENDING = "SAVE_PAGE_PENDING";
export const SAVE_PAGE_SUCCESS = "SAVE_PAGE_SUCCESS";
export const SAVE_PAGE_FAILURE = "SAVE_PAGE_FAILURE";
